baseurl = "https://carloscastellanosvera.com"
title = "Carlos Castellanos Vera / ccverak"
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsUseClassic = false
pygmentsStyle = "monokai" # or dracula; Color-theme or style for syntax highlighting.
pygmentsCodefences = false # Enable code fence background highlighting.
pygmentsCodefencesGuessSyntax = false # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = false # new add
#pygmentsOptions = ["linenos"]

disable_comments = true
disqusShortname = "ccverakblog" # Enable or disable Disqus.

googleAnalytics = "UA-108083906-1"
enableRobotsTXT = true
canonifyURLs = true
uglyurls = false
summaryLength = 30
# enableEmoji = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/posts/:title"

[params]
    title = "Carlos Castellanos Vera / ccverak"
    author = "Carlos Castellanos Vera"
    description = "Carlos Castellanos Vera is a Software Engineer and Solutions Architect located in Malaga, Spain with over 10 years of experience."
    keywords = "software,engineer,developer,serverless,aws,amazon,architect,freelancer,contractor,ruby,nodejs"
    info = "Sr. Software Engineer. Solutions Architect."
    avatarurl = "/images/av2.jpg"
    footercontent = ""

    fixedbarContent = "Do you want to contact me? → " # Add fixedbar content
    fixedbarContentAfter = "me@carloscastellanosvera.com" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/av2.jpg" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.
    twitterHandle = "ccverak"

# Social links
[[params.social]]
    name = "/Github"
    weight = 1
    url = "https://github.com/ccverak/"
[[params.social]]
    name = "/LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/ccverak/"
[[params.social]]
    name = "/Twitter"
    weight = 3
    url = "https://twitter.com/ccverak/"
[[params.social]]
    name = "/Blog"
    weight = 4
    url = "https://carloscastellanosvera.com/posts"

# Menu links
[[menu.main]]
    name = "/Blog"
    weight = 1
    url  = "/posts/"

[[menu.main]]
    name = "/About"
    weight = 2
    url  = "/about/"
