baseurl = "https://carloscastellanosvera.com"
title = ""
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

googleAnalytics = "UA-108083906-1"
enableRobotsTXT = "true"

[params] # theme parameters
    author = "Carlos Castellanos Vera"
    description = "Carlos Castellanos Vera is a Software Engineer and Solutions Architect located in Malaga, Spain with over 10 years of experience."
    keywords = "software,engineer,developer,serverless,aws,amazon,architect,freelancer,contractor,ruby,nodejs"
    info = "Sr. Software Engineer. Solutions Architect."
    avatarurl = "/images/av2.jpg"
    footercontent = ""

    fixedbarContent = "Do you want to contact me? →" # Add fixedbar content
    fixedbarContentAfter = "Drop me an email to → me@carloscastellanosvera.com" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = ["custom.css"]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/av2.jpg" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "/Github"
    weight = 1
    url = "https://github.com/ccverak/"
[[params.social]]
    name = "/LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/ccverak/"
[[params.social]]
    name = "/Twitter"
    weight = 3
    url = "https://twitter.com/ccverak/"

# Menu links
[[menu.main]]
    name = "/Blog"
    weight = 1
    url  = "https://medium.com/@ccverak"
